#!/bin/sh
# Copyright (C) 2012-2014 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>
# 	Author: AHMED Zribi <ahmed.zribi@pivasoftware.com>
# Copyright (C) 2011-2012 Luka Perkov <freecwmp@lukaperkov.net>

get_capabilities_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.Capabilities." "" "0"
	;;
esac
}

get_capabilities_diagnostic_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.Capabilities.PerformanceDiagnostic." "" "0"
	;;
esac
}

get_capabilities_diagnostic_download_transports() {
	local param="InternetGatewayDevice.Capabilities.PerformanceDiagnostic.DownloadTransports"
	local nl="$1"
	local val=""
	local permissions="0"
	case "$action" in
		get_value)
			val="HTTP"
			;;
		get_name)
			[ "$nl" = "1" ] && return $E_INVALID_ARGUMENTS
			;;
		get_notification)
			easycwmp_get_parameter_notification "val" "$param"
			;;
	esac
	easycwmp_output "$param" "$val" "$permissions"
	return 0
}

get_capabilities_diagnostic_upload_transports() {
	local param="InternetGatewayDevice.Capabilities.PerformanceDiagnostic.UploadTransports"
	local nl="$1"
	local val=""
	local permissions="0"
	case "$action" in
		get_value)
			val="HTTP"
			;;
		get_name)
			[ "$nl" = "1" ] && return $E_INVALID_ARGUMENTS
			;;
		get_notification)
			easycwmp_get_parameter_notification "val" "$param"
			;;
	esac
	easycwmp_output "$param" "$val" "$permissions"
	return 0
}

get_capabilities_diagnostic() {
case "$1" in
	InternetGatewayDevice.)
		get_capabilities_object 0
		get_capabilities_diagnostic_object "$2"
		get_capabilities_diagnostic_download_transports "$2"
		get_capabilities_diagnostic_upload_transports "$2"
		return 0
		;;

	InternetGatewayDevice.Capabilities.)
		get_capabilities_object "$2"
		get_capabilities_diagnostic_object 0
		get_capabilities_diagnostic_download_transports "$2"
		get_capabilities_diagnostic_upload_transports "$2"
		return 0
		;;

	InternetGatewayDevice.Capabilities.PerformanceDiagnostic.)
		get_capabilities_diagnostic_object "$2"
		get_capabilities_diagnostic_download_transports 0
		get_capabilities_diagnostic_upload_transports 0
		return 0
		;;

	InternetGatewayDevice.Capabilities.PerformanceDiagnostic.DownloadTransports)
		get_capabilities_diagnostic_download_transports "$2"
		return $?
		;;

	InternetGatewayDevice.Capabilities.PerformanceDiagnostic.UploadTransports)
		get_capabilities_diagnostic_upload_transports "$2"
		return $?
		;;
esac

return $E_INVALID_PARAMETER_NAME
}

set_capabilities_diagnostic() {
case "$1" in
	InternetGatewayDevice.|\
	InternetGatewayDevice.Capabilities.|\
	InternetGatewayDevice.Capabilities.PerformanceDiagnostic.)
		set_node_readonly_and_reject_notification_info
		return $?
		;;

	InternetGatewayDevice.Capabilities.PerformanceDiagnostic.DownloadTransports|\
	InternetGatewayDevice.Capabilities.PerformanceDiagnostic.UploadTransports)
		set_node_readonly_info "$1" "$2"
		return $?
		;;

esac

return $E_INVALID_PARAMETER_NAME
}

build_instances_capabilities_diagnostic() { return 0; }

add_object_capabilities_diagnostic() { return $E_INVALID_PARAMETER_NAME; }

delete_object_capabilities_diagnostic() { return $E_INVALID_PARAMETER_NAME; }
